### PR TITLE
Remove trailing dashes in tag names

### PR DESCRIPTION
**Pull request by Mojken**
Git allows them, but not Github

### CODE REVIEW

**Review by tobias5m — APPROVED** [review]
LGTM

**Review by Swamii — APPROVED** [review]
⭐

**Comment by flaeppe** [comment]
Seems that `dist/index.js` wasn't fully in sync when merging this(?)

Have a look at #33 to see if it looks correct

**Comment by Swamii** [comment]
> Seems that `dist/index.js` wasn't fully in sync when merging this(?)
> 
> 
> 
> Have a look at #33 to see if it looks correct

Yes seems like it. @Mojken Should it be reverted to the dist-version or not?

**Comment by Mojken** [comment]
The `dist/index.js` in #33 is correct, without it there all spaces are removed, rather than turned into dashes, which is obviously very bad. Good idea with the action!

**Pull request merged**
