### PR TITLE
Make valid release message configurable

### PR DESCRIPTION
**Pull request by antonagestam**
- Changed to use @vercel/ncc@0.27.0, as the project seem to have moved.

### CODE REVIEW

**Review by hannseman — APPROVED** [review]
Super 👍

**Comment by antonagestam** [comment]
@hannseman Forgot to add docs for the new config option 😌

**Comment by hannseman** [comment]
@antonagestam would you like to run a `npm run package` and push the new dist/index.js?

**Comment by antonagestam** [comment]
@hannseman Done! No idea whether or not the large diff in dist/index.js makes sense though ...

**Pull request merged**
